# -*- coding: utf-8 -*-
"""
Building the CRYPTO AI Trading BOT Using Machine Learning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TRzqYfLdarN9hzziOYuWhaF9m9tbEIPu

**Install Dependencies**
"""

"""**Import dependencies**"""

import os
import pandas as pd
import yfinance as yf
import alpaca as tradeapi
import alpaca_trade_api as tradeapi
import configparser
import pytz
import locale
import pandas_market_calendars as mcal

from alpaca_trade_api.rest import REST, TimeFrame, APIError
import alpaca_trade_api as alpaca
from ta.volatility import BollingerBands
from ta.momentum import RSIIndicator
from ta.trend import sma_indicator
from tqdm import tqdm
from requests_html import HTMLSession
from datetime import datetime
from slack import WebClient
from slack.errors import SlackApiError
import time
from alpaca.data.historical import CryptoHistoricalDataClient
from alpaca.data.requests import CryptoBarsRequest
from alpaca.data.timeframe import TimeFrame
from alpaca.trading.client import TradingClient
from alpaca.trading.requests import MarketOrderRequest
from alpaca.trading.enums import OrderSide, TimeInForce
from datetime import datetime
from dateutil.relativedelta import relativedelta
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Activation, Dense, Dropout, LSTM
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.metrics import mean_absolute_error
import json
import logging
#import config
import asyncio
from lumibot.brokers import Alpaca
from lumibot.backtesting import YahooDataBacktesting
from lumibot.strategies.strategy import Strategy
from lumibot.traders import Trader
from datetime import datetime
from alpaca_trade_api import REST
#from timedelta import Timedelta
time.sleep(1)
from google.colab import drive
drive.mount('/content/drive')



"""**Building the CRYPTO AI Trading BOT Using Machine Learning**

---

Machine learning empowers traders to accelerate and automate one of the most complex, time-consuming, and challenging aspects of algorithmic trading, providing a competitive advantage beyond rules-based trading.

**What are we building?**

We're building a **trading bot** that uses a **LSTM model** to predict the **closing price** of **OUR ASSETS** on Alpaca.

We'll use **market data** from Alpaca to train our model and use the predicted closing price from the trained model to make necessary trading decisions.

To start, we can consider two scenarios:

If we do not have a position and the current price of the asset is less than the predicted price of the asset at some time in the future. In this scenario, we place a **BUY** market order for a fixed quantity of the asset.

If we do have a position and the current price of the asset is more than the predicted price of the asset at some time in the future. In this scenario we place a **SELL** market order for a fixed quantity of the asset.

**Grabs the HIGHEST VALUED (HV) (top traded crypto assets by market cap) crypto assets from YahooFinance! to determine trading opportunities using simple technical trading indicators such as Bollinger Bands and RSI.**

**Grabs the MOST ACTIVE (MA) crypto assets from YahooFinance! to determine trading opportunities using simple technical trading indicators such as Bollinger Bands and RSI.**

**Grabs the TOP GAINERS (TG) crypto assets from YahooFinance! to determine trading opportunities using simple technical trading indicators such as Bollinger Bands and RSI.**

**Grabs the TOP LOSERS (TL) crypto assets from YahooFinance! to determine trading opportunities using simple technical trading indicators such as Bollinger Bands and RSI.**

**Grabs the TRENDING NOW (TN) crypto assets from YahooFinance! to determine trading opportunities using simple technical trading indicators such as Bollinger Bands and RSI.**

**We enable logging to monitor the latest prices and bot status.**

**Define some trading variables that we will use to trade our assets. This includes the trading pair, the quantity to buy for each trade, current position, current price of the asset and the predicted price of the asset.**

**Build the Stock Prediction Class**

**Create a helper function that returns the current position of the asset pair in our account.**

**Build the Bot's order execution method**

**Build the Trading Logic for the Bot**

**Build the main.py — Bringing It All Together**

**Finally, we use the asyncio module to run our main function in a loop.**
"""

class TradingOpportunitiesHV:
    def __init__(self, n_stocks=0, n_crypto=100):
        """
        Description:
        Grabs top stock losers and highest valued crypto assets from YahooFinance! to determine trading opportunities using simple technical trading indicators
        such as Bollinger Bands and RSI.

        Arguments:
            •  n_stocks: number of top losing stocks that'll be pulled from YahooFinance! and considered in the algo
            •  n_crypto: number of top traded and most valuable crypto assets that'll be pulled from YahooFinance! and considered in the algo

        Methods:
            • raw_get_daily_info(): Grabs a provided site and transforms HTML to a pandas df
            • get_trading_opportunities(): Grabs df from raw_get_daily_info() and provides just the top "n" losers declared by user in n_stocks and "n" amount of top of most popular crypto assets to examine
            • get_asset_info(): a df can be provided to specify which assets you'd like info for since this method is used in the Alpaca class. If no df argument is passed then tickers from get_trading_opportunities() method are used.
        """

        self.n_stocks = n_stocks
        self.n_crypto = n_crypto

    def raw_get_daily_info(self, site):
        """
        Description:
        Grabs a provided site and transforms HTML to a pandas df

        Argument(s):
            • site: YahooFinance! top losers website provided in the get_day_losers() function below

        Other Notes:
        Commented out the conversion of market cap and volume from string to float since this threw an error.
        Can grab this from the yfinance API if needed or come back to this function and fix later.
        """

        session = HTMLSession()
        response = session.get(site)

        tables = pd.read_html(response.html.raw_html)
        df = tables[0].copy()
        df.columns = tables[0].columns

        session.close()
        return df

    def get_trading_opportunities(self, n_stocks=None, n_crypto=None):
        """
        Description:
        Grabs df from raw_get_daily_info() and provides just the top "n" losers
        declared by user in n_stocks and "n" amount of top of most popular crypto
        assets to examine

        This method scrapes YahooFinance! using the yfinance package to obtain
        the top losing stocks of the day and most popular crypto assets. It first
        gets the top losing stocks by percentage change for the day using
        get_day_losers. Then, it obtains the top traded crypto assets by market cap
        using get_top_crypto.

        Argument(s):
            • n_stocks: Number of top losers to analyze per YahooFinance! top losers
             site.
            • n_crypto: Number of most popular crypto assets to grab historical price
            info from.
        """

        #####################
        #####################
        # Crypto part
        df_crypto = []
        i = 0
        while True:
            try:
                df_crypto.append(
                    self.raw_get_daily_info(
                        "https://finance.yahoo.com/crypto?offset={}&count=100".format(i)
                    )
                )
                i += 100
                print("processing " + i)
            except:
                break

        df_crypto = pd.concat(df_crypto)
        df_crypto["asset_type"] = "crypto"

        #df_crypto = df_crypto.head(self.n_crypto)
        df_crypto = df_crypto

        #####################
        #####################
        # Stock part
        df_stock = self.raw_get_daily_info(
            "https://finance.yahoo.com/losers?offset=0&count=100"
        )
        df_stock["asset_type"] = "stock"

        df_stock = df_stock.head(self.n_stocks)

        #####################
        #####################
        # Merge df's and return as one
        dfs = [df_crypto, df_stock]
        df_opportunitiesHV = pd.concat(dfs, axis=0).reset_index(drop=True)

        # Create a list of all tickers scraped
        self.all_tickers = list(df_opportunitiesHV["Symbol"])

        return df_opportunitiesHV

    def get_asset_info(self, df=None):
        """
        Description:
        Grabs historical prices for assets, calculates RSI and Bollinger Bands tech
        signals, and returns a df with all this data for the assets meeting the
        buy criteria.

        This method filters the list of assets obtained from get_trading_opportunities
        by checking each asset's technical indicators and picking just the oversold
        assets as buying opportunities.

        Argument(s):
            • df: a df can be provided to specify which assets you'd like info for
            since this method is used in the Alpaca class. If no df argument is
            passed then tickers from get_trading_opportunities() method are used.
        """

        # Grab technical stock info:
        if df is None:
            all_tickers = self.all_tickers
        else:
            all_tickers = list(df["yf_ticker"])
        print(all_tickers)

        df_tech = []
        for i, symbol in tqdm(
            enumerate(all_tickers),
            desc="• Grabbing technical metrics for "
            + str(len(all_tickers))
            + " assets",
        ):
            try:
                Ticker = yf.Ticker(symbol)
                Hist = Ticker.history(period="1y", interval="1d")

                # Check if the historical data is empty
                if Hist.empty:
                    print(f"No historical data found for {symbol}, skipping...")
                    continue  # Skip to the next ticker
                    #print(Hist)

                for n in [14, 30, 50, 200]:
                # These technical indicators are commonly used in financial
                # analysis and algorithmic trading to assess trends, momentum,
                # and volatility.
                    # Initialize MA Indicator
                    # Simple Moving Average (SMA)
                    Hist["ma" + str(n)] = sma_indicator(
                        close=Hist["Close"], window=n, fillna=False
                    )
                    # Initialize RSI Indicator
                    # Relative Strength Index (RSI)
                    Hist["rsi" + str(n)] = RSIIndicator(
                        close=Hist["Close"], window=n
                    ).rsi()
                    # Initialize Hi BB Indicator
                    # Bollinger Band High Indicator
                    Hist["bbhi" + str(n)] = BollingerBands(
                        close=Hist["Close"], window=n, window_dev=2
                    ).bollinger_hband_indicator()
                    # Initialize Lo BB Indicator
                    # Bollinger Band Low Indicator
                    Hist["bblo" + str(n)] = BollingerBands(
                        close=Hist["Close"], window=n, window_dev=2
                    ).bollinger_lband_indicator()

                df_tech_temp = Hist.iloc[-1:].reset_index(drop=True)
                df_tech_temp.insert(0, "Symbol", Ticker.ticker)
                df_tech.append(df_tech_temp)
            except KeyError:
                print(f"KeyError encountered for {symbol}, skipping...")
            except Exception as e:
                print(f"An unexpected error occurred for {symbol}: {e}")

        # Check if df_tech is still empty after the loop
        if not df_tech:
            print("No data found for any of the tickers. Returning an empty DataFrame.")
            return pd.DataFrame()  # Return empty DataFrame to avoid the error
        #df_tech = [x for x in df_tech if not x.empty]
        df_tech = pd.concat(df_tech)

        # Define the buy criteria
        buy_criteria = (
            (df_tech[["bblo14", "bblo30", "bblo50", "bblo200"]] == 1).any(axis=1)
        ) | ((df_tech[["rsi14", "rsi30", "rsi50", "rsi200"]] <= 30).any(axis=1))

        # Filter the DataFrame
        buy_filtered_df_HV = df_tech[buy_criteria]

        # Create a list of tickers to trade
        self.buy_tickers = list(buy_filtered_df_HV["Symbol"])

        return buy_filtered_df_HV

n_stocks=0
n_crypto=100

# Instantiate TradingOpportunities class
trades = TradingOpportunitiesHV(n_stocks=n_stocks, n_crypto=n_crypto)

# Shows all scraped opportunities; defaults to 100 top losing stocks and 100
# of the most popular crypto assets
df_opportunitiesHV = trades.get_trading_opportunities()
print('==========================================================================')
print(
    "• Scraped the HIGHEST VALUED crypto assets opportunities: " + str(
    df_opportunitiesHV.to_markdown()))

# The all_tickers attribute is a list of all tickers in the get_trading_opportunities()
# method. Passing this list through the get_asset_info() method shows just the
# tickers that meet buying criteria
buy_filtered_df_HV = trades.get_asset_info()
print('==========================================================================')
print("• oversold HV assets meeting the buy criteria as buying opportunities: " + str(
    buy_filtered_df_HV))
print('==========================================================================')
print("• list of HV to trade: " + str(list(buy_filtered_df_HV["Symbol"])))
print('==========================================================================')


class TradingOpportunitiesMA:
    def __init__(self, n_stocks=0, n_crypto=100):
        self.n_stocks = n_stocks
        self.n_crypto = n_crypto
    def raw_get_daily_info(self, site):
        session = HTMLSession()
        response = session.get(site)
        tables = pd.read_html(response.html.raw_html)
        df = tables[0].copy()
        df.columns = tables[0].columns
        session.close()
        return df
    def get_trading_opportunities(self, n_stocks=None, n_crypto=None):
        # Crypto part
        df_crypto = []
        i = 0
        while True:
            try:
                df_crypto.append(
                    self.raw_get_daily_info(
                        "https://finance.yahoo.com/markets/crypto/most-active/?start=0&count=100".format(i)
                    )
                )
                i += 100
                print("processing " + i)
            except:
                break
        df_crypto = pd.concat(df_crypto)
        df_crypto["asset_type"] = "crypto"
        #df_crypto = df_crypto.head(self.n_crypto)
        df_crypto = df_crypto
        # Stock part
        df_stock = self.raw_get_daily_info(
            "https://finance.yahoo.com/losers?offset=0&count=100"
        )
        df_stock["asset_type"] = "stock"

        df_stock = df_stock.head(self.n_stocks)
        # Merge df's and return as one
        dfs = [df_crypto, df_stock]
        df_opportunitiesMA = pd.concat(dfs, axis=0).reset_index(drop=True)
        # Create a list of all tickers scraped
        self.all_tickers = list(df_opportunitiesMA["Symbol"])
        return df_opportunitiesMA

    def get_asset_info(self, df=None):
        # Grab technical stock info:
        if df is None:
            all_tickers = self.all_tickers
        else:
            all_tickers = list(df["yf_ticker"])
        print(all_tickers)

        df_tech = []
        for i, symbol in tqdm(
            enumerate(all_tickers),
            desc="• Grabbing technical metrics for "
            + str(len(all_tickers))
            + " assets",
        ):
            try:
                Ticker = yf.Ticker(symbol)
                Hist = Ticker.history(period="1y", interval="1d")

                # Check if the historical data is empty
                if Hist.empty:
                    print(f"No historical data found for {symbol}, skipping...")
                    continue  # Skip to the next ticker
                    #print(Hist)

                for n in [14, 30, 50, 200]:
                    # Simple Moving Average (SMA)
                    Hist["ma" + str(n)] = sma_indicator(
                        close=Hist["Close"], window=n, fillna=False
                    )
                    # Initialize RSI Indicator
                    # Relative Strength Index (RSI)
                    Hist["rsi" + str(n)] = RSIIndicator(
                        close=Hist["Close"], window=n
                    ).rsi()
                    # Initialize Hi BB Indicator
                    # Bollinger Band High Indicator
                    Hist["bbhi" + str(n)] = BollingerBands(
                        close=Hist["Close"], window=n, window_dev=2
                    ).bollinger_hband_indicator()
                    # Initialize Lo BB Indicator
                    # Bollinger Band Low Indicator
                    Hist["bblo" + str(n)] = BollingerBands(
                        close=Hist["Close"], window=n, window_dev=2
                    ).bollinger_lband_indicator()

                df_tech_temp = Hist.iloc[-1:].reset_index(drop=True)
                df_tech_temp.insert(0, "Symbol", Ticker.ticker)
                df_tech.append(df_tech_temp)
            except KeyError:
                print(f"KeyError encountered for {symbol}, skipping...")
            except Exception as e:
                print(f"An unexpected error occurred for {symbol}: {e}")

        # Check if df_tech is still empty after the loop
        if not df_tech:
            print("No data found for any of the tickers. Returning an empty DataFrame.")
            return pd.DataFrame()  # Return empty DataFrame to avoid the error
        #df_tech = [x for x in df_tech if not x.empty]
        df_tech = pd.concat(df_tech)

        # Define the buy criteria
        buy_criteria = (
            (df_tech[["bblo14", "bblo30", "bblo50", "bblo200"]] == 1).any(axis=1)
        ) | ((df_tech[["rsi14", "rsi30", "rsi50", "rsi200"]] <= 30).any(axis=1))

        # Filter the DataFrame
        buy_filtered_df_MA = df_tech[buy_criteria]

        # Create a list of tickers to trade
        self.buy_tickers = list(buy_filtered_df_MA["Symbol"])

        return buy_filtered_df_MA

n_stocks=0
n_crypto=100

# Instantiate TradingOpportunities class
trades = TradingOpportunitiesMA(n_stocks=n_stocks, n_crypto=n_crypto)

# Shows all scraped opportunities; defaults to 100 top losing stocks and 100
# of the most popular crypto assets
df_opportunitiesMA = trades.get_trading_opportunities()
print('==========================================================================')
print(
    "• Scraped the MOST ACTIVE crypto assets opportunities: " + str(
    df_opportunitiesMA.to_markdown()))
buy_filtered_df_MA = trades.get_asset_info()
print('==========================================================================')
print("• oversold MA assets meeting the buy criteria as buying opportunities: " + str(
    buy_filtered_df_MA))
print('==========================================================================')
print("• list of MA to trade: " + str(list(buy_filtered_df_MA["Symbol"])))
print('==========================================================================')

class TradingOpportunitiesTG:
    def __init__(self, n_stocks=0, n_crypto=100):
        self.n_stocks = n_stocks
        self.n_crypto = n_crypto
    def raw_get_daily_info(self, site):
        session = HTMLSession()
        response = session.get(site)
        tables = pd.read_html(response.html.raw_html)
        df = tables[0].copy()
        df.columns = tables[0].columns
        session.close()
        return df
    def get_trading_opportunities(self, n_stocks=None, n_crypto=None):
        # Crypto part
        df_crypto = []
        i = 0
        while True:
            try:
                df_crypto.append(
                    self.raw_get_daily_info(
                        "https://finance.yahoo.com/markets/crypto/gainers/?start=0&count=100".format(i)
                    )
                )
                i += 100
                print("processing " + i)
            except:
                break
        df_crypto = pd.concat(df_crypto)
        df_crypto["asset_type"] = "crypto"
        #df_crypto = df_crypto.head(self.n_crypto)
        df_crypto = df_crypto
        # Stock part
        df_stock = self.raw_get_daily_info(
            "https://finance.yahoo.com/losers?offset=0&count=100"
        )
        df_stock["asset_type"] = "stock"

        df_stock = df_stock.head(self.n_stocks)
        # Merge df's and return as one
        dfs = [df_crypto, df_stock]
        df_opportunitiesTG = pd.concat(dfs, axis=0).reset_index(drop=True)
        # Create a list of all tickers scraped
        self.all_tickers = list(df_opportunitiesTG["Symbol"])
        return df_opportunitiesTG

    def get_asset_info(self, df=None):
        # Grab technical stock info:
        if df is None:
            all_tickers = self.all_tickers
        else:
            all_tickers = list(df["yf_ticker"])
        print(all_tickers)

        df_tech = []
        for i, symbol in tqdm(
            enumerate(all_tickers),
            desc="• Grabbing technical metrics for "
            + str(len(all_tickers))
            + " assets",
        ):
            try:
                Ticker = yf.Ticker(symbol)
                Hist = Ticker.history(period="1y", interval="1d")

                # Check if the historical data is empty
                if Hist.empty:
                    print(f"No historical data found for {symbol}, skipping...")
                    continue  # Skip to the next ticker
                    #print(Hist)

                for n in [14, 30, 50, 200]:
                    # Simple Moving Average (SMA)
                    Hist["ma" + str(n)] = sma_indicator(
                        close=Hist["Close"], window=n, fillna=False
                    )
                    # Initialize RSI Indicator
                    # Relative Strength Index (RSI)
                    Hist["rsi" + str(n)] = RSIIndicator(
                        close=Hist["Close"], window=n
                    ).rsi()
                    # Initialize Hi BB Indicator
                    # Bollinger Band High Indicator
                    Hist["bbhi" + str(n)] = BollingerBands(
                        close=Hist["Close"], window=n, window_dev=2
                    ).bollinger_hband_indicator()
                    # Initialize Lo BB Indicator
                    # Bollinger Band Low Indicator
                    Hist["bblo" + str(n)] = BollingerBands(
                        close=Hist["Close"], window=n, window_dev=2
                    ).bollinger_lband_indicator()

                df_tech_temp = Hist.iloc[-1:].reset_index(drop=True)
                df_tech_temp.insert(0, "Symbol", Ticker.ticker)
                df_tech.append(df_tech_temp)
            except KeyError:
                print(f"KeyError encountered for {symbol}, skipping...")
            except Exception as e:
                print(f"An unexpected error occurred for {symbol}: {e}")

        # Check if df_tech is still empty after the loop
        if not df_tech:
            print("No data found for any of the tickers. Returning an empty DataFrame.")
            return pd.DataFrame()  # Return empty DataFrame to avoid the error
        #df_tech = [x for x in df_tech if not x.empty]
        df_tech = pd.concat(df_tech)

        # Define the buy criteria
        buy_criteria = (
            (df_tech[["bblo14", "bblo30", "bblo50", "bblo200"]] == 1).any(axis=1)
        ) | ((df_tech[["rsi14", "rsi30", "rsi50", "rsi200"]] <= 30).any(axis=1))

        # Filter the DataFrame
        buy_filtered_df_TG = df_tech[buy_criteria]

        # Create a list of tickers to trade
        self.buy_tickers = list(buy_filtered_df_TG["Symbol"])

        return buy_filtered_df_TG

n_stocks=0
n_crypto=100

# Instantiate TradingOpportunities class
trades = TradingOpportunitiesTG(n_stocks=n_stocks, n_crypto=n_crypto)

# Shows all scraped opportunities; defaults to 100 top losing stocks and 100
# of the most popular crypto assets
df_opportunitiesTG = trades.get_trading_opportunities()
print('==========================================================================')
print(
    "• Scraped the TOP GAINERS crypto assets opportunities: " + str(
    df_opportunitiesTG.to_markdown()))
buy_filtered_df_TG = trades.get_asset_info()
print('==========================================================================')
print("• oversold TG assets meeting the buy criteria as buying opportunities: " + str(
    buy_filtered_df_TG))
print('==========================================================================')
print("• list of TG to trade: " + str(list(buy_filtered_df_TG["Symbol"])))
print('==========================================================================')

class TradingOpportunitiesTL:
    def __init__(self, n_stocks=0, n_crypto=100):
        self.n_stocks = n_stocks
        self.n_crypto = n_crypto
    def raw_get_daily_info(self, site):
        session = HTMLSession()
        response = session.get(site)
        tables = pd.read_html(response.html.raw_html)
        df = tables[0].copy()
        df.columns = tables[0].columns
        session.close()
        return df
    def get_trading_opportunities(self, n_stocks=None, n_crypto=None):
        # Crypto part
        df_crypto = []
        i = 0
        while True:
            try:
                df_crypto.append(
                    self.raw_get_daily_info(
                        "https://finance.yahoo.com/markets/crypto/losers/?start=0&count=100".format(i)
                    )
                )
                i += 100
                print("processing " + i)
            except:
                break
        df_crypto = pd.concat(df_crypto)
        df_crypto["asset_type"] = "crypto"
        #df_crypto = df_crypto.head(self.n_crypto)
        df_crypto = df_crypto
        # Stock part
        df_stock = self.raw_get_daily_info(
            "https://finance.yahoo.com/losers?offset=0&count=100"
        )
        df_stock["asset_type"] = "stock"

        df_stock = df_stock.head(self.n_stocks)
        # Merge df's and return as one
        dfs = [df_crypto, df_stock]
        df_opportunitiesTL = pd.concat(dfs, axis=0).reset_index(drop=True)
        # Create a list of all tickers scraped
        self.all_tickers = list(df_opportunitiesTL["Symbol"])
        return df_opportunitiesTL

    def get_asset_info(self, df=None):
        # Grab technical stock info:
        if df is None:
            all_tickers = self.all_tickers
        else:
            all_tickers = list(df["yf_ticker"])
        print(all_tickers)

        df_tech = []
        for i, symbol in tqdm(
            enumerate(all_tickers),
            desc="• Grabbing technical metrics for "
            + str(len(all_tickers))
            + " assets",
        ):
            try:
                Ticker = yf.Ticker(symbol)
                Hist = Ticker.history(period="1y", interval="1d")

                # Check if the historical data is empty
                if Hist.empty:
                    print(f"No historical data found for {symbol}, skipping...")
                    continue  # Skip to the next ticker
                    #print(Hist)

                for n in [14, 30, 50, 200]:
                    # Simple Moving Average (SMA)
                    Hist["ma" + str(n)] = sma_indicator(
                        close=Hist["Close"], window=n, fillna=False
                    )
                    # Initialize RSI Indicator
                    # Relative Strength Index (RSI)
                    Hist["rsi" + str(n)] = RSIIndicator(
                        close=Hist["Close"], window=n
                    ).rsi()
                    # Initialize Hi BB Indicator
                    # Bollinger Band High Indicator
                    Hist["bbhi" + str(n)] = BollingerBands(
                        close=Hist["Close"], window=n, window_dev=2
                    ).bollinger_hband_indicator()
                    # Initialize Lo BB Indicator
                    # Bollinger Band Low Indicator
                    Hist["bblo" + str(n)] = BollingerBands(
                        close=Hist["Close"], window=n, window_dev=2
                    ).bollinger_lband_indicator()

                df_tech_temp = Hist.iloc[-1:].reset_index(drop=True)
                df_tech_temp.insert(0, "Symbol", Ticker.ticker)
                df_tech.append(df_tech_temp)
            except KeyError:
                print(f"KeyError encountered for {symbol}, skipping...")
            except Exception as e:
                print(f"An unexpected error occurred for {symbol}: {e}")

        # Check if df_tech is still empty after the loop
        if not df_tech:
            print("No data found for any of the tickers. Returning an empty DataFrame.")
            return pd.DataFrame()  # Return empty DataFrame to avoid the error
        #df_tech = [x for x in df_tech if not x.empty]
        df_tech = pd.concat(df_tech)

        # Define the buy criteria
        buy_criteria = (
            (df_tech[["bblo14", "bblo30", "bblo50", "bblo200"]] == 1).any(axis=1)
        ) | ((df_tech[["rsi14", "rsi30", "rsi50", "rsi200"]] <= 30).any(axis=1))

        # Filter the DataFrame
        buy_filtered_df_TL = df_tech[buy_criteria]

        # Create a list of tickers to trade
        self.buy_tickers = list(buy_filtered_df_TL["Symbol"])

        return buy_filtered_df_TL

n_stocks=0
n_crypto=100

# Instantiate TradingOpportunities class
trades = TradingOpportunitiesTL(n_stocks=n_stocks, n_crypto=n_crypto)

# Shows all scraped opportunities; defaults to 100 top losing stocks and 100
# of the most popular crypto assets
df_opportunitiesTL = trades.get_trading_opportunities()
print('==========================================================================')
print(
    "• Scraped the TOP LOSERS crypto assets opportunities: " + str(
    df_opportunitiesTL.to_markdown()))
buy_filtered_df_TL = trades.get_asset_info()
print('==========================================================================')
print("• oversold TL assets meeting the buy criteria as buying opportunities: " + str(
    buy_filtered_df_TL))
print('==========================================================================')
print("• list of TL to trade: " + str(list(buy_filtered_df_TL["Symbol"])))
print('==========================================================================')

class TradingOpportunitiesTN:
    def __init__(self, n_stocks=0, n_crypto=100):
        self.n_stocks = n_stocks
        self.n_crypto = n_crypto
    def raw_get_daily_info(self, site):
        session = HTMLSession()
        response = session.get(site)
        tables = pd.read_html(response.html.raw_html)
        df = tables[0].copy()
        df.columns = tables[0].columns
        session.close()
        return df
    def get_trading_opportunities(self, n_stocks=None, n_crypto=None):
        # Crypto part
        df_crypto = []
        i = 0
        while True:
            try:
                df_crypto.append(
                    self.raw_get_daily_info(
                        "https://finance.yahoo.com/markets/crypto/trending/".format(i)
                    )
                )
                i += 100
                print("processing " + i)
            except:
                break
        df_crypto = pd.concat(df_crypto)
        df_crypto["asset_type"] = "crypto"
        #df_crypto = df_crypto.head(self.n_crypto)
        df_crypto = df_crypto
        # Stock part
        df_stock = self.raw_get_daily_info(
            "https://finance.yahoo.com/losers?offset=0&count=100"
        )
        df_stock["asset_type"] = "stock"

        df_stock = df_stock.head(self.n_stocks)
        # Merge df's and return as one
        dfs = [df_crypto, df_stock]
        df_opportunitiesTN = pd.concat(dfs, axis=0).reset_index(drop=True)
        # Create a list of all tickers scraped
        self.all_tickers = list(df_opportunitiesTN["Symbol"])
        return df_opportunitiesTN

    def get_asset_info(self, df=None):
        # Grab technical stock info:
        if df is None:
            all_tickers = self.all_tickers
        else:
            all_tickers = list(df["yf_ticker"])
        print(all_tickers)

        df_tech = []
        for i, symbol in tqdm(
            enumerate(all_tickers),
            desc="• Grabbing technical metrics for "
            + str(len(all_tickers))
            + " assets",
        ):
            try:
                Ticker = yf.Ticker(symbol)
                Hist = Ticker.history(period="1y", interval="1d")

                # Check if the historical data is empty
                if Hist.empty:
                    print(f"No historical data found for {symbol}, skipping...")
                    continue  # Skip to the next ticker
                    #print(Hist)

                for n in [14, 30, 50, 200]:
                    # Simple Moving Average (SMA)
                    Hist["ma" + str(n)] = sma_indicator(
                        close=Hist["Close"], window=n, fillna=False
                    )
                    # Initialize RSI Indicator
                    # Relative Strength Index (RSI)
                    Hist["rsi" + str(n)] = RSIIndicator(
                        close=Hist["Close"], window=n
                    ).rsi()
                    # Initialize Hi BB Indicator
                    # Bollinger Band High Indicator
                    Hist["bbhi" + str(n)] = BollingerBands(
                        close=Hist["Close"], window=n, window_dev=2
                    ).bollinger_hband_indicator()
                    # Initialize Lo BB Indicator
                    # Bollinger Band Low Indicator
                    Hist["bblo" + str(n)] = BollingerBands(
                        close=Hist["Close"], window=n, window_dev=2
                    ).bollinger_lband_indicator()

                df_tech_temp = Hist.iloc[-1:].reset_index(drop=True)
                df_tech_temp.insert(0, "Symbol", Ticker.ticker)
                df_tech.append(df_tech_temp)
            except KeyError:
                print(f"KeyError encountered for {symbol}, skipping...")
            except Exception as e:
                print(f"An unexpected error occurred for {symbol}: {e}")

        # Check if df_tech is still empty after the loop
        if not df_tech:
            print("No data found for any of the tickers. Returning an empty DataFrame.")
            return pd.DataFrame()  # Return empty DataFrame to avoid the error
        #df_tech = [x for x in df_tech if not x.empty]
        df_tech = pd.concat(df_tech)

        # Define the buy criteria
        buy_criteria = (
            (df_tech[["bblo14", "bblo30", "bblo50", "bblo200"]] == 1).any(axis=1)
        ) | ((df_tech[["rsi14", "rsi30", "rsi50", "rsi200"]] <= 30).any(axis=1))

        # Filter the DataFrame
        buy_filtered_df_TN = df_tech[buy_criteria]

        # Create a list of tickers to trade
        self.buy_tickers = list(buy_filtered_df_TN["Symbol"])

        return buy_filtered_df_TN

n_stocks=0
n_crypto=100

# Instantiate TradingOpportunities class
trades = TradingOpportunitiesTN(n_stocks=n_stocks, n_crypto=n_crypto)

# Shows all scraped opportunities; defaults to 100 top losing stocks and 100
# of the most popular crypto assets
df_opportunitiesTN = trades.get_trading_opportunities()
print('==========================================================================')
print(
    "• Scraped the TRENDING NOW crypto assets opportunities: " + str(
    df_opportunitiesTN.to_markdown()))
buy_filtered_df_TN = trades.get_asset_info()
print('==========================================================================')
print("• oversold TN assets meeting the buy criteria as buying opportunities: " + str(
    buy_filtered_df_TN))
print('==========================================================================')
print("• list of TN to trade: " + str(list(buy_filtered_df_TN)))
print('==========================================================================')

# ENABLE LOGGING - options, DEBUG,INFO, WARNING?
# We enable logging to monitor the latest prices and bot status.
logging.basicConfig(level=logging.INFO,
                   format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

config_path = "/content/drive/MyDrive/creds.cfg"
config = configparser.ConfigParser()
config.read(config_path)

# Alpaca Trading Client
trading_client = TradingClient(
   config["alpaca"]["KEY_ID"], config["alpaca"]["SECRET_KEY"], paper=True)
# set to use a live trading environment by setting the paper parameter as False

# Define some trading variables that we will use to trade our assets.
# This includes the trading pair, the quantity to buy for each trade,
# current position, current price of the asset and the predicted price of the asset.
# Trading variables

print('==========================================================================')
nyse = pytz.timezone('America/New_York')
current_time = datetime.now(nyse).strftime("%Y-%m-%d %H:%M:%S")
print(current_time)
print("• Current Time: " + str(current_time))
print('==========================================================================')

combined_df = pd.concat([buy_filtered_df_HV,
                         buy_filtered_df_MA,
                         buy_filtered_df_TG,
                         buy_filtered_df_TL,
                         buy_filtered_df_TN])

trading_pair = combined_df["Symbol"].str.replace('-', '/').unique().tolist()

total_count = len(trading_pair)
print(f"• My Trading Pair Total Count: {total_count}")
print('==========================================================================')

qty_to_trade = 1
# Wait time between each bar request and model training
waitTime = 3600
data = 0
current_position, current_price = 0, 0
predicted_price = 0
print('==========================================================================')
#print("• My Trading Pair: " + str(trading_pair))
print(
    "• My Trading Pair as at New York City Current Time (" + current_time + "): " + str(trading_pair))
print('==========================================================================')

# Build the Stock Prediction Class

# The __init__() method initializes the variables needed to filter our market data
# and train the AI model. These include parameters like lookback period (period to
# consider in the past to make a future prediction), number of neurons/nodes that
# will be part of each layer of our LSTM mode, loss function, activation function,
# number of epochs to train our model for, optimizer, batch size and the output size.

class stockPred:
    def __init__(self,
                 past_days: int = 50,
                 trading_pair: str = 'ETHUSD',
                 exchange: str = 'FTXU',
                 feature: str = 'close',

                 look_back: int = 100,

                 neurons: int = 50,
                 activ_func: str = 'linear',
                 dropout: float = 0.2,
                 loss: str = 'mse',
                 optimizer: str = 'adam',
                 epochs: int = 20,
                 batch_size: int = 32,
                 output_size: int = 1
                 ):
        self.exchange = exchange
        self.feature = feature

        self.look_back = look_back

        self.neurons = neurons
        self.activ_func = activ_func
        self.dropout = dropout
        self.loss = loss
        self.optimizer = optimizer
        self.epochs = epochs
        self.batch_size = batch_size
        self.output_size = output_size

    def getAllData(self):
        # getAllData() method helps us get the raw market data that we need to
        # train the model.
        # First, it instantiates a data client using Alpaca-py. Then we create a
        # CryptoBarRequest() and pass in the necessary parameters like symbol,
        # timeframe of the data we would like and the start time of the data.
        # we change the symbol parameter to something like this - ETHUSD for the
        # market data request. We are also requesting the data to be in hourly
        # time frame and start 1000 hours before the current time.
        # We then Pass in the request we just created to the get_crypto_bars()
        # method returns the needed bar data. Now that we have the necessary
        # bar data, we set the current price of the asset to be the last
        # closing price in the bar data and finally return the bar data of the
        # asset.

        # Alpaca Market Data Client
        data_client = CryptoHistoricalDataClient()

        time_diff = datetime.now() - relativedelta(hours=1000)
        logger.info("Getting bar data for {0} starting from {1}".format(
            trading_pair, time_diff))
        # Defining Bar data request parameters
        request_params = CryptoBarsRequest(
            symbol_or_symbols=[trading_pair],
            timeframe=TimeFrame.Hour,
            start=time_diff
        )
        # Get the bar data from Alpaca
        df = data_client.get_crypto_bars(request_params).df
        global current_price
        current_price = df.iloc[-1]['close']
        return df

    def getFeature(self, df):
        # getFeature() method extracts the price column we are looking to predict.
        # Since we are looking to predict the closing price of the asset, we filter
        # only the ‘close’ column of the bar data and return it.
        data = df.filter([self.feature])
        data = data.values
        return data

    def scaleData(self, data):
        # scaleData() helps us transform our bar data we just requested from Alpaca.
        # This is to avoid outliers skewing the interpretation of the data in a
        # certain direction resulting in a biased output. To help scale the data,
        # we use sklearn’s MinMaxScaler() method to scale our closing prices in
        # the range (-1,1).
        scaler = MinMaxScaler(feature_range=(-1, 1))
        scaled_data = scaler.fit_transform(data)
        return scaled_data, scaler

    # train on all data for which labels are available (train + test from dev)
    def getTrainData(self, scaled_data):
        # getTrainData() is one of the most important methods in the class.
        # It creates the shape of our training data. If we are looking at market
        # data 1000 hours in the past from our current time with each hour
        # being its own row, then it will create a 3D array of size (900, 100, 1).
        # This means it will create 900 samples with each sample being 100 hours to
        # look in the back (look_back) and 1 forward looking result value.
        x, y = [], []
        for price in range(self.look_back, len(scaled_data)):
            x.append(scaled_data[price - self.look_back:price, :])
            y.append(scaled_data[price, :])
        return np.array(x), np.array(y)

    # Creates the LSTM model

    # It starts by instantiating a Sequential model and followed by adding LSTM
    # layers on it. We need to specify the number of neurons in each LSTM layer.
    # In this casse, we are using 50 neurons for each LSTM layer. A LSTM layer
    # is usually followed by a Dropout layer. The Dropout layer randomly sets
    # input units to 0 with a frequency of rate at each step during training time,
    # which helps prevent overfitting. In total 3 LSTM layers are added followed
    # by a Dropout layer each. This is followed by adding a final Dense layer
    # and then passing the result through an activation function. We are using
    # a linear activation function here. Now that the model is created, we can
    # configure the model with the loss function and optimizer we would like to
    # use. We are using the Mean Squared Error loss function and Adam optimizer
    # in our case.

    def LSTM_model(self, input_data):
        model = Sequential()
        model.add(LSTM(self.neurons, input_shape=(
            input_data.shape[1], input_data.shape[2]), return_sequences=True))
        model.add(Dropout(self.dropout))
        model.add(LSTM(self.neurons, return_sequences=True))
        model.add(Dropout(self.dropout))
        model.add(LSTM(self.neurons))
        model.add(Dropout(self.dropout))
        model.add(Dense(units=self.output_size))
        model.add(Activation(self.activ_func))

        model.compile(loss=self.loss, optimizer=self.optimizer)
        return model

    def trainModel(self, x, y):
        # trainModel() uses the x and y arrays from getTrainData() method to feed
        # the training data to our LSTM model we created in the previous snippet
        # and then trains it. The necessary training data x_train and y_train are
        # extracted from the arrays that are fed in. Calling model.fit() method
        # trains our model on the training data we just prepared. Along with the
        # training data, we pass it the number of epochs we need our model to train
        # and the batch size of the data being fed.

        x_train = x[: len(x) - 1]
        y_train = y[: len(x) - 1]
        model = self.LSTM_model(x_train)
        modelfit = model.fit(x_train, y_train, epochs=self.epochs,
                             batch_size=self.batch_size, verbose=1, shuffle=True)
        return model, modelfit

    def predictModel(self):
        # calls all the functions we defined above in the class. It starts by
        # getting the necessary bar data for our asset. This is followed by
        # extracting the feature (closing price), scaling the data and then
        # extracting the training data for our model. Once we have the training
        # data ready, trainModel() is called. It creates and trains the model
        # with the parameters we define along with feeding it the training data.
        # Now that we have our model trained, we also need to prepare the data
        # that we need to predict on. For this we select the last 100 hours
        # (look_back period) of data to look back at to predict 1 hour into the
        # future. Remember, we only had 900 samples in our training data? The
        # last 100 samples are to predict the next hour’s closing price.Once the
        # data we need to predict on, is ready, we can execute the coolest part
        # of the entire bot, predicting the closing price of the asset for the
        # next hour. This is done by calling model.predict() method. The result
        # from this operation is then reshaped. Remember that the data we have
        # been feeding the model and its output are still scaled. This means
        # they lie in the range (-1,1). Now that we have our result in this range,
        # we can inverse transform it using the scaler object we used to scale our
        # data in the first place. This returns our true predicted closing price for
        # the next hour.

        logger.info("Getting The Asset Bar Data")
        # get all data
        df = self.getAllData()

        logger.info("Getting Feature: {}".format(self.feature))
        # get feature (closing price)
        data = self.getFeature(df)

        logger.info("Scaling Data")
        # scale data and get scaler
        scaled_data, scaler = self.scaleData(data)

        logger.info("Getting Train Data")
        # get train data
        x_train, y_train = self.getTrainData(scaled_data)

        logger.info("Training Model")
        # Creates and returns a trained model
        model = self.trainModel(x_train, y_train)[0]

        logger.info("Extracting data to predict on")
        # Extract the Closing prices that need to be fed into predict the result
        x_pred = scaled_data[-self.look_back:]
        x_pred = np.reshape(x_pred, (1, x_pred.shape[0]))

        # Predict the result
        logger.info("Predicting Price")
        pred = model.predict(x_pred).squeeze()
        pred = np.array([float(pred)])
        pred = np.reshape(pred, (pred.shape[0], 1))

        # Inverse the scaling to get the actual price
        pred_true = scaler.inverse_transform(pred)
        return pred_true[0][0]

trading_pair = trading_pair[0] # The first item in our assets list
'''pred = stockPred()
#current_price = pred.getAllData()
#data = pred.getFeature(current_price)
#scaled_data, scaler = pred.scaleData(data)
#x, y = pred.getTrainData(scaled_data)
predicted_price = pred.predictModel()'''

# Create a helper function that returns the current position of the
# asset pair in our account. It uses the get_all_positions() method from our
# trading client to retrieve the position and then assigns it to current_position.

def get_positions():
    positions = trading_client.get_all_positions()
    # print(positions[0])
    global current_position
    for p in positions:
        if p.symbol == trading_pair:
            current_position = p.qty
            return current_position
    return current_position

# Build the Bot's order execution method

# Based on the side of the trade, we create a market order request using Alpaca-py's
# MarketOrderRequest() method. Here, we can specify the symbol of the asset,
# quantity of the asset we would like to trade, the side of the trade and time
# till when the order should stay in place (time_in_force). market order request
# we just created can then be submitted as an order using our trading client's
# submit_order() method. Once the orders are placed, we return the response
# object from Alpaca.

async def post_alpaca_order(side):
    '''
    Post an order to Alpaca
    '''
    try:
        if side == 'buy':
            market_order_data = MarketOrderRequest(
                symbol=trading_pair,
                qty=qty_to_trade,
                side=OrderSide.BUY,
                time_in_force=TimeInForce.GTC
            )
            buy_order = trading_client.submit_order(
                order_data=market_order_data
            )
            return buy_order
        else:
            market_order_data = MarketOrderRequest(
                symbol=trading_pair,
                qty=current_position,
                side=OrderSide.SELL,
                time_in_force=TimeInForce.GTC
            )
            sell_order = trading_client.submit_order(
                order_data=market_order_data
            )
            return sell_order
    except Exception as e:
        logger.exception(
            "There was an issue posting order to Alpaca: {0}".format(e))
        return False

# Build the Trading Logic for the Bot

# It takes into account the current price, predicted price of the asset pair and
# also its position in our Alpaca account.
# The logic states that if we do not have a position and the current price of
# the asset is less than its predicted price one hour from now, then we buy 1
# qty. Since we are testing this on a paper trading account, we can trade any
# arbitrary amount greater than the minimum amount required to trade on Alpaca.
# The minimum amount of Ethereum we can trade on Alpaca is 0.01 ETH.
# Information about other cryptocurrencies and their minimum tradable quantity
# on Alpaca can be found https://docs.alpaca.markets/docs/crypto-trading-1
# On the other hand, if we have an asset position and the predicted price of
# the asset is below its current price, we choose to sell.
# More checks and balances can be added to optimize trading performance in
# the snippet above. For example, one might consider calculating fees involved
# in executing trades, loss cutting or even adding a minimum profit threshold.

async def check_condition():
    '''
    Strategy:
    - If the predicted price an hour from now is above the current price and we
    do not have a position, buy
    - If the predicted price an hour from now is below the current price and
    we do have a position, sell
    '''
    global current_position, current_price, predicted_price
    current_position = get_positions()
    logger.info("Current Price is: {0}".format(current_price))
    logger.info("Current Position is: {0}".format(current_position))
    # If we do not have a position and current price is less than the predicted price place a market buy order
    if float(current_position) <= 0.01 and current_price < predicted_price:
        logger.info("Placing Buy Order")
        buy_order = await post_alpaca_order('buy')
        if buy_order:
            logger.info("Buy Order Placed")

    # If we do have a position and current price is greater than the predicted price place a market sell order
    if float(current_position) >= 0.01 and current_price > predicted_price:
        logger.info("Placing Sell Order")
        sell_order = await post_alpaca_order('sell')
        if sell_order:
            logger.info("Sell Order Placed")

# Build the main.py — Bringing It All Together

# We are predicting the closing price of our asset one hour into the future
# The function runs a never ending loop that predicts the price of our asset
# at a later point in time and makes trading decisions based on the predicted
# price, current price of the asset and position of the asset in our account.
# We start by creating an instance of class stockPred and call it pred.
# We then call the predictModel() method that returns the predicted price of our
# asset at a later point in time.
# Once we have the predicted price, we call the function check_condition()
# that computes if a trade should be made.
# After waiting for a waitTime amount of seconds this process repeats again.
# We have set the waitTime to 3600 seconds to wait for 1hr before we check for
# a trade again. This can be changed based on the timeframe of data you are
# looking at.
# Since we are considering an hourly timeframe and predicting the closing price
# of our asset one hour into the future, it is reasonable to keep it at 3600
# seconds.

# Get latest asset data and check possible trade conditions
async def main():
    '''
    Main function to get latest asset data and check possible trade conditions
    '''
    while True:
        logger.info('----------------------------------------------------')

        pred = stockPred()
        global predicted_price
        predicted_price = pred.predictModel()
        logger.info("Predicted Price is {0}".format(predicted_price))
        l1 = loop.create_task(check_condition())
        await asyncio.wait([l1])
        await asyncio.sleep(waitTime)

# Finally, we use the asyncio module to run our main function in a loop.

#loop = asyncio.get_event_loop()
#loop.run_until_complete(main())
#loop.close()

loop = asyncio.get_event_loop()
loop.create_task(main())
